[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  NODE_VERSION = "18"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions."scheduled-reminders"]
  schedule = "@hourly"