[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  NODE_VERSION = "18"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Scheduled function to process notifications every 5 minutes
# [[functions]]
#   schedule = "*/5 * * * *"
#   function = "scheduled-notifications"